### ISSUE TITLE
Ошибка 500, но все работает

### ISSUE THREAD

**Issue by bbekaa** [KloopMedia/GigaTurnip#100]
![image](https://user-images.githubusercontent.com/100202857/182529403-58906da5-a4dd-4c25-a252-6a227e8f063b.png)

ошибка 500 выходит, на это форму настроен таскавард: сама форма completion, по кондишну создается verified stage и сразу автокомплитится. все это работает, только выходит ошибка 500.
campaign:7.chain:100.stage:481

была еще одна ошибка 500, но она исчезла

**Comment by Kabirov7** [comment]
@bbekaa можешь подробнее расписать стейдж, который комплитишь и выходящие из него(который комплитишь) стейджи

**Comment by bbekaa** [comment]
@Kabirov7 
![image](https://user-images.githubusercontent.com/100202857/183563179-dc7ec0d2-68dd-4336-bba9-8a0b0ccca29c.png)
В Registration есть поле на который настроен кондитион, в зависимости от него срабатывает та или иная часть цепи. Речь идет о правой части. Completetion: Registration, Verification: Автокомплит если первый, Rank: student_1. Когда я выбираю ответ, который должен заставляет работать кондишн "если первый", выходит ошибка 500. Когда выбираю ответ для "если не первый" все хорошо.

**Comment by Kabirov7** [comment]
The problem was in query complexity, when system tries to get user's tasks
