### ISSUE TITLE
Сабмитится null response и обрывается цепь

### ISSUE THREAD

**Issue by bbekaa** [KloopMedia/GigaTurnip#40]
Есть такая проблема, но она нечастая:
Иногда форма, где есть required вопросы, сабмитится без заполнения. Мы не знаем как это получается и не можем воспроизвести эту ошибку. И в таком случае цепь обрывается и следующая форма не появляется.

**Comment by Kabirov7** [comment]
@Rinatius может сделаем валидатор на бэкенде где скрипт достает обязательные поля и проверяет респонсы?

**Comment by Rinatius** [comment]
Да
