### ISSUE TITLE
Во фронте не удаляется стрелка, приходится идти в админку

### ISSUE THREAD

**Issue by almazbekovaaizi** [KloopMedia/GigaTurnip#5]
> Когда пытаешься удалить уже существующую стрелку во фронтенде, то она не удаляется. 

![photo_2022-02-22_17-13-03](https://user-images.githubusercontent.com/94098794/155121242-112f6c89-773a-44f8-b621-6398a9f30797.jpg)

**Comment by Kabirov7** [comment]
Пока система не дает права на удаление из фронтенда, потому что страшно. Я думаю что скоро такие возможности начнут появляться.
