### ISSUE TITLE
ошибка 500 при длинном названии стейджа

### ISSUE THREAD

**Issue by bbekaa** [KloopMedia/GigaTurnip#83]
![image](https://user-images.githubusercontent.com/100202857/178493072-bc68eae7-d5b3-4022-88dd-75f8b62368f6.png)
при очень длинном названии стейджа выдало ошибку 500, Ринат попросил добавить, чтобы такие ошибки четко обозначались

**Comment by Kabirov7** [comment]
@bbekaa у стейджей есть ограничение на название, всего 100 символов.
Штука которая будет грамотно обозначать ошибки в системе скоро начнет разрабатываться.
